=== hettan/tddd43/lab1/xml_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="db">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="topics">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="topic" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="name" type="xs:string"/>
                                        <xs:element name="text" type="xs:string"/>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:ID" use="required"/>
                                    <xs:attribute name="originator" type="xs:IDREF" use="required"/>
                                    <xs:attribute name="parent" type="xs:IDREF"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="experts">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="expert" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="name" type="xs:string"/>
                                        <xs:element name="email" type="xs:string"/>
                                        <xs:element name="description" type="xs:string"/>
                                        <xs:element name="expertizes">
                                            <xs:complexType>
                                                <xs:sequence maxOccurs="unbounded">
                                                    <xs:element name="expertize">
                                                        <xs:complexType>
                                                            <xs:attribute name="topic" type="xs:IDREF" use="required"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="recommendations">
                                            <xs:complexType>
                                                <xs:sequence maxOccurs="unbounded" minOccurs="0">
                                                    <xs:element name="recommendation">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="text" type="xs:string"/>
                                                            </xs:sequence>
                                                            <xs:attribute name="recommendee" type="xs:IDREF" use="required"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    
                                    <xs:attribute name="id" type="xs:ID" use="required"/>
                                </xs:complexType>
                             
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>

<!-- keys -->
        <xs:key name="expert_key">
            <xs:selector xpath=".//expert"/>
            <xs:field xpath="@id"/>
        </xs:key>
        <xs:key name="topic_key">
            <xs:selector xpath=".//topic"/>
            <xs:field xpath="@id"/>
        </xs:key>

<!-- key refs -->
        <xs:keyref name="originator_ref" refer="expert_key">
            <xs:selector xpath=".//topic"/>
            <xs:field xpath="@originator"/>
        </xs:keyref>
        <xs:keyref name="expertize_ref" refer="topic_key">
            <xs:selector xpath=".//expertize"/>
            <xs:field xpath="@topic"/>
        </xs:keyref>
        <xs:keyref name="recommendee_ref" refer="expert_key">
            <xs:selector xpath=".//recommendation"/>
            <xs:field xpath="@recommendee"/>
        </xs:keyref>
        <xs:keyref name="parent_topic_ref" refer="topic_key">
            <xs:selector xpath=".//topic"/>
            <xs:field xpath="@parent"/>
        </xs:keyref>
        
    </xs:element>
</xs:schema>

=== hettan/tddd43/lab1/instance2.xml
<?xml version="1.0" encoding="UTF-8"?>
<expert xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/home/jacob/courses/tddd43/lab1/xml_schema.xsd">
    <id>
    </id>
    <name>name0</name>
    <email>email0</email>
    <description>
        <text>text0</text>
    </description>
    <expertizes>
    </expertizes>
    <expertizes>
    </expertizes>
</expert>

=== hettan/tddd43/lab1/xml_data.xml
<?xml version="1.0" encoding="UTF-8"?>
<db xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/home/jacob/courses/tddd43/lab1/xml_schema.xsd">
    <topics>
        <topic id="ID005" originator="ID002">
            <name>Computer Science</name>
            <text>It's fun!</text>
        </topic>
        <topic id="ID000" originator="ID002" parent="ID005">
            <name>Java</name>
            <text>An object oriented language</text>
        </topic>
        <topic id="ID001" originator="ID003" parent="ID005">
            <name>XML</name>
            <text>Use JSON instead! :)</text>
        </topic>
    </topics>
    <experts>
        <expert id="ID002">
            <name>Jacob</name>
            <email>jacho391@student.liu.se</email>
            <description>Im a student!</description>
            <expertizes>
                <expertize topic="ID000"/>
                <expertize topic="ID001"/>
            </expertizes>
            <recommendations>
                <recommendation recommendee="ID010">
                    <text>Good at XML!</text>
                </recommendation>
            </recommendations>
        </expert>
        <expert id="ID003">
            <name>Oliver</name>
            <email>olist125@student.liu.se</email>
            <description>Im a professor!</description>
            <expertizes>
                <expertize topic="ID001"/>
            </expertizes>
            <recommendations>
                <recommendation recommendee="ID002">
                    <text>He's awesome!</text>
                </recommendation>
            </recommendations>
        </expert>
        <expert id="ID010">
            <name>John</name>
            <email>john@doe.se</email>
            <description>Im not a student!</description>
            <expertizes>
                <expertize topic="ID000"/>
                <expertize topic="ID001"/>
            </expertizes>
            <recommendations>
              
            </recommendations>
        </expert>
    </experts>
</db>
